# Generated by Django 4.1.7 on 2023-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='price',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
