# Generated by Django 4.1.7 on 2023-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_remove_advertisement_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='video',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='изображение или видео'),
        ),
    ]
