# Generated by Django 4.1.7 on 2023-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_remove_advertisement_video_advertisement_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='media',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Обложка'),
        ),
    ]
