# Generated by Django 4.1.7 on 2023-11-27 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisements', '0008_advertisement_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description_task', models.TextField(verbose_name='Задание')),
                ('created_at_task', models.DateTimeField(auto_now_add=True)),
                ('update_at_task', models.DateTimeField(auto_now=True)),
                ('image_task', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Обложка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
