# Generated by Django 4.1.7 on 2023-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_task',
            field=models.IntegerField(default=1, verbose_name='Баллы'),
        ),
    ]
