# Generated by Django 4.1.7 on 2023-11-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0011_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
