# Generated by Django 4.1.7 on 2023-11-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0012_alter_cart_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
